import type { Config } from "tailwindcss"
const convertToRGB = (variableName: string) => `rgba(var(${variableName}))`;

const config = {
  darkMode: ["class"],
  content: [
    './pages/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './app/**/*.{ts,tsx}',
    './src/**/*.{ts,tsx}',
  ],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      boxShadow: {
        "custom-shadow-2xs": "var(--color-shadow-2xs)",
        "custom-shadow-xs": "var(--color-shadow-xs)",
        "custom-shadow-sm": "var(--color-shadow-sm)",
        "custom-shadow-rg": "var(--color-shadow-rg)",
        "custom-shadow-md": "var(--color-shadow-md)",
        "custom-shadow-lg": "var(--color-shadow-lg)",
        "custom-shadow-xl": "var(--color-shadow-xl)",
        "custom-shadow-2xl": "var(--color-shadow-2xl)",
        "custom-shadow-3xl": "var(--color-shadow-3xl)",
        "custom-shadow-4xl": "var(--color-shadow-4xl)",
        "custom-sidebar-shadow-2xs": "var(--color-sidebar-shadow-2xs)",
        "custom-sidebar-shadow-xs": "var(--color-sidebar-shadow-xs)",
        "custom-sidebar-shadow-sm": "var(--color-sidebar-shadow-sm)",
        "custom-sidebar-shadow-rg": "var(--color-sidebar-shadow-rg)",
        "custom-sidebar-shadow-md": "var(--color-sidebar-shadow-md)",
        "custom-sidebar-shadow-lg": "var(--color-sidebar-shadow-lg)",
        "custom-sidebar-shadow-xl": "var(--color-sidebar-shadow-xl)",
        "custom-sidebar-shadow-2xl": "var(--color-sidebar-shadow-2xl)",
        "custom-sidebar-shadow-3xl": "var(--color-sidebar-shadow-3xl)",
        "custom-sidebar-shadow-4xl": "var(--color-sidebar-shadow-4xl)",
        "onboarding-shadow-sm": "var(--color-onboarding-shadow-sm)",
      },
      colors: {
        border: "var(--border)",
        input: "var(--input)",
        ring: "var(--ring)",
        background: "var(--background)",
        foreground: "var(--foreground)",
        primary: {
          0: "rgb(255, 255, 255)",
          10: "var(--color-primary-10)",
          20: "var(--color-primary-20)",
          30: "var(--color-primary-30)",
          40: "var(--color-primary-40)",
          50: "var(--color-primary-50)",
          60: "var(--color-primary-60)",
          70: "var(--color-primary-70)",
          80: "var(--color-primary-80)",
          90: "var(--color-primary-90)",
          100: "var(--color-primary-100)",
          200: "var(--color-primary-200)",
          300: "var(--color-primary-300)",
          400: "var(--color-primary-400)",
          500: "var(--color-primary-500)",
          600: "var(--color-primary-600)",
          700: "var(--color-primary-700)",
          800: "var(--color-primary-800)",
          900: "var(--color-primary-900)",
          1000: "rgb(0, 0, 0)",
          DEFAULT: "var(--color-primary-100)",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        custom: {
          primary: {
            0: "rgb(255, 255, 255)",
            10: "var(--color-primary-10)",
            20: "var(--color-primary-20)",
            30: "var(--color-primary-30)",
            40: "var(--color-primary-40)",
            50: "var(--color-primary-50)",
            60: "var(--color-primary-60)",
            70: "var(--color-primary-70)",
            80: "var(--color-primary-80)",
            90: "var(--color-primary-90)",
            100: "var(--color-primary-100)",
            200: "var(--color-primary-200)",
            300: "var(--color-primary-300)",
            400: "var(--color-primary-400)",
            500: "var(--color-primary-500)",
            600: "var(--color-primary-600)",
            700: "var(--color-primary-700)",
            800: "var(--color-primary-800)",
            900: "var(--color-primary-900)",
            1000: "rgb(0, 0, 0)",
            DEFAULT: "var(--color-primary-100)",
          },
          auth: {
            background: {
              100: "var(--color-auth-background-100)",
              200: "var(--color-auth-background-200)",
              300: "var(--color-auth-background-300)",
              400: "var(--color-auth-background-400)",
            },
            text: {
              90: "var(--color-auth-text-90)",
              100: "var(--color-auth-text-100)",
              200: "var(--color-auth-text-200)",
              300: "var(--color-auth-text-300)",
              400: "var(--color-auth-text-400)",
            },
            border: {
              100: "var(--color-auth-border-100)",
              200: "var(--color-auth-border-200)",
              300: "var(--color-auth-border-300)",
            },
          },
          text: {
            0: "rgb(255, 255, 255)",
            10: "var(--color-text-10)",
            20: "var(--color-text-20)",
            30: "var(--color-text-30)",
            40: "var(--color-text-40)",
            50: "var(--color-text-50)",
            60: "var(--color-text-60)",
            70: "var(--color-text-70)",
            80: "var(--color-text-80)",
            90: "var(--color-text-90)",
            100: "var(--color-text-100)",
            200: "var(--color-text-200)",
            300: "var(--color-text-300)",
            400: "var(--color-text-400)",
            500: "var(--color-text-500)",
            600: "var(--color-text-600)",
            700: "var(--color-text-700)",
            800: "var(--color-text-800)",
            900: "var(--color-text-900)",
            1000: "rgb(0, 0, 0)",
            DEFAULT: "var(--color-text-100)",
          },
          background: {
            0: "rgb(255, 255, 255)",
            10: "var(--color-background-10)",
            20: "var(--color-background-20)",
            30: "var(--color-background-30)",
            40: "var(--color-background-40)",
            50: "var(--color-background-50)",
            60: "var(--color-background-60)",
            70: "var(--color-background-70)",
            80: "var(--color-background-80)",
            90: "var(--color-background-90)",
            100: "var(--color-background-100)",
            200: "var(--color-background-200)",
            300: "var(--color-background-300)",
            400: "var(--color-background-400)",
            500: "var(--color-background-500)",
            600: "var(--color-background-600)",
            700: "var(--color-background-700)",
            800: "var(--color-background-800)",
            900: "var(--color-background-900)",
            1000: "rgb(0, 0, 0)",
            DEFAULT: "var(--color-background-100)",
          },
          border: {
            0: "rgb(255, 255, 255)",
            100: "var(--color-border-100)",
            200: "var(--color-border-200)",
            300: "var(--color-border-300)",
            400: "var(--color-border-400)",
            1000: "rgb(0, 0, 0)",
            DEFAULT: "var(--color-border-200)",
          },
          backdrop: "rgba(0, 0, 0, 0.25)",
        }
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "caret-blink": {
          "0%,70%,100%": { opacity: "1" },
          "20%,50%": { opacity: "0" },
        },
      },
      typography: () => ({
        brand: {
          css: {
            "--tw-prose-body": "var(--color-text-100)",
            "--tw-prose-p": "var(--color-text-100)",
            "--tw-prose-headings": "var(--color-text-100)",
            "--tw-prose-lead": "var(--color-text-100)",
            "--tw-prose-links": "var(--color-primary-100)",
            "--tw-prose-bold": "var(--color-text-100)",
            "--tw-prose-counters": "var(--color-text-100)",
            "--tw-prose-bullets": "var(--color-text-100)",
            "--tw-prose-hr": "var(--color-text-100)",
            "--tw-prose-quotes": "var(--color-text-100)",
            "--tw-prose-quote-borders": "var(--color-border-200)",
            "--tw-prose-code": "var(--color-text-100)",
            "--tw-prose-pre-code": "var(--color-text-100)",
            "--tw-prose-pre-bg": "var(--color-background-100)",
            "--tw-prose-th-borders": "var(--color-border-200)",
            "--tw-prose-td-borders": "var(--color-border-200)",
          },
        },
      }),
      fontSize: {
        xs: "0.675rem",
        sm: "0.7875rem",
        base: "0.9rem",
        lg: "1.0125rem",
        xl: "1.125rem",
        "2xl": "1.35rem",
        "3xl": "1.6875rem",
        "4xl": "2.25rem",
        "5xl": "2.7rem",
        "6xl": "3.375rem",
        "7xl": "4.05rem",
        "8xl": "5.4rem",
        "9xl": "7.2rem",
      },
      screens: {
        "3xl": "1792px",
      },
      gap: {
        0: "0",
        0.5: "0.1125rem",
        1: "0.225rem",
        1.5: "0.3375rem",
        2: "0.45rem",
        2.5: "0.5625rem",
        3: "0.675rem",
        3.5: "0.7875rem",
        4: "0.9rem",
        5: "1.125rem",
        6: "1.35rem",
        7: "1.575rem",
        8: "1.8rem",
        9: "2.025rem",
        10: "2.25rem",
        11: "2.475rem",
        12: "2.7rem",
        16: "3.6rem",
        20: "4.5rem",
        24: "5.4rem",
        32: "7.2rem",
        40: "9rem",
        48: "10.8rem",
        56: "12.6rem",
        64: "14.4rem",
        72: "16.2rem",
        80: "18rem",
        96: "21.6rem",
      },
      margin: {
        0: "0",
        0.5: "0.1125rem",
        1: "0.225rem",
        1.5: "0.3375rem",
        2: "0.45rem",
        2.5: "0.5625rem",
        3: "0.675rem",
        3.5: "0.7875rem",
        4: "0.9rem",
        5: "1.125rem",
        6: "1.35rem",
        7: "1.575rem",
        8: "1.8rem",
        9: "2.025rem",
        10: "2.25rem",
        11: "2.475rem",
        12: "2.7rem",
        16: "3.6rem",
        20: "4.5rem",
        24: "5.4rem",
        32: "7.2rem",
        40: "9rem",
        48: "10.8rem",
        56: "12.6rem",
        64: "14.4rem",
        72: "16.2rem",
        80: "18rem",
        96: "21.6rem",
      },
      padding: {
        0: "0",
        0.5: "0.1125rem",
        1: "0.225rem",
        1.5: "0.3375rem",
        2: "0.45rem",
        2.5: "0.5625rem",
        3: "0.675rem",
        3.5: "0.7875rem",
        4: "0.9rem",
        5: "1.125rem",
        6: "1.35rem",
        7: "1.575rem",
        8: "1.8rem",
        9: "2.025rem",
        10: "2.25rem",
        11: "2.475rem",
        12: "2.7rem",
        16: "3.6rem",
        20: "4.5rem",
        24: "5.4rem",
        32: "7.2rem",
        40: "9rem",
        48: "10.8rem",
        56: "12.6rem",
        64: "14.4rem",
        72: "16.2rem",
        80: "18rem",
        96: "21.6rem",
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "caret-blink": "caret-blink 1.25s ease-out infinite",
      },
      backgroundImage: {
        "onboarding-gradient-100": "var( --gradient-onboarding-100)",
        "onboarding-gradient-200": "var( --gradient-onboarding-200)",
        "onboarding-gradient-300": "var( --gradient-onboarding-300)",
      },
    },
    fontFamily: {
      custom: ["Inter", "sans-serif"],
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config

export default config