enum ESignInSteps {
    EMAIL = "EMAIL",
    PASSWORD = "PASSWORD",
    UNIQUE_CODE = "UNIQUE_CODE",
    OPTIONAL_SET_PASSWORD = "OPTIONAL_SET_PASSWORD",
    USE_UNIQUE_CODE_FROM_PASSWORD = "USE_UNIQUE_CODE_FROM_PASSWORD",
}

export default ESignInSteps